#ifndef MC_ENUM_H
#define MC_ENUM_H

#include <mc/data/str.h>

#define MC_DEFINE_ENUM_ITEM(NAME, PREFIX) PREFIX ## NAME,

#define _MC_ENUM_ITEM_TO_STRING(NAME, RESULT, PREFIX) case PREFIX ## NAME: (RESULT) = #NAME; break;
#define MC_ENUM_TO_STRING(RESULT, ENUM, ENUM_ITER, PREFIX) \
    switch ((ENUM)){ ENUM_ITER(_MC_ENUM_ITEM_TO_STRING, RESULT, PREFIX) }

#define _MC_ENUM_ITEM_FROM_STR(NAME, STR, RESULT, PREFIX) if(mc_str_equ(STR, MC_STRC(#NAME))) RESULT = PREFIX##NAME; else
#define MC_ENUM_FROM_STR(RESULT, STR, ENUM_ITER, PREFIX) \
    ENUM_ITER(_MC_ENUM_ITEM_FROM_STR, STR, RESULT, PREFIX)

#endif // MC_ENUM_H
