#ifndef MC_XLIBWM_KEY_H
#define MC_XLIBWM_KEY_H

#define MC_X11_ITER_KEYS() \
    MC_XKEY(BackSpace,       BACKSPACE) \
    MC_XKEY(Tab,             TAB) \
    MC_XKEY(Linefeed,        LINEFEED) \
    MC_XKEY(Clear,           CLEAR) \
    MC_XKEY(Return,          RETURN) \
    MC_XKEY(Pause,           PAUSE) \
    MC_XKEY(Scroll_Lock,     SCROLL_LOCK) \
    MC_XKEY(Sys_Req,         SYS_REQ) \
    MC_XKEY(Escape,          ESCAPE) \
    MC_XKEY(Delete,          DELETE) \
    MC_XKEY(Home,            HOME) \
    MC_XKEY(Left,            LEFT) \
    MC_XKEY(Up,              UP) \
    MC_XKEY(Right,           RIGHT) \
    MC_XKEY(Down,            DOWN) \
    MC_XKEY(Page_Up,         PAGE_UP) \
    MC_XKEY(Page_Down,       PAGE_DOWN) \
    MC_XKEY(End,             END) \
    MC_XKEY(Begin,           BEGIN) \
    MC_XKEY(Select,          SELECT) \
    MC_XKEY(Print,           PRINT) \
    MC_XKEY(Execute,         EXECUTE) \
    MC_XKEY(Insert,          INSERT) \
    MC_XKEY(Undo,            UNDO) \
    MC_XKEY(Redo,            REDO) \
    MC_XKEY(Menu,            MENU) \
    MC_XKEY(Find,            FIND) \
    MC_XKEY(Cancel,          CANCEL) \
    MC_XKEY(Help,            HELP) \
    MC_XKEY(Break,           BREAK) \
    MC_XKEY(Mode_switch,     MODE_SWITCH) \
    MC_XKEY(Num_Lock,        NUM_LOCK) \
    MC_XKEY(KP_Space,        KP_SPACE) \
    MC_XKEY(KP_Tab,          KP_TAB) \
    MC_XKEY(KP_Enter,        KP_ENTER) \
    MC_XKEY(KP_F1,           KP_F1) \
    MC_XKEY(KP_F2,           KP_F2) \
    MC_XKEY(KP_F3,           KP_F3) \
    MC_XKEY(KP_F4,           KP_F4) \
    MC_XKEY(KP_Home,         KP_HOME) \
    MC_XKEY(KP_Left,         KP_LEFT) \
    MC_XKEY(KP_Up,           KP_UP) \
    MC_XKEY(KP_Right,        KP_RIGHT) \
    MC_XKEY(KP_Down,         KP_DOWN) \
    MC_XKEY(KP_End,          KP_END) \
    MC_XKEY(KP_Begin,        KP_BEGIN) \
    MC_XKEY(KP_Insert,       KP_INSERT) \
    MC_XKEY(KP_Delete,       KP_DELETE) \
    MC_XKEY(KP_Equal,        KP_EQUAL) \
    MC_XKEY(KP_Multiply,     KP_MULTIPLY) \
    MC_XKEY(KP_Add,          KP_ADD) \
    MC_XKEY(KP_Separator,    KP_SEPARATOR) \
    MC_XKEY(KP_Subtract,    KP_SUBSTRACT) \
    MC_XKEY(KP_Decimal,      KP_DECIMAL) \
    MC_XKEY(KP_Divide,       KP_DIVIDE) \
    MC_XKEY(KP_0,            KP_0) \
    MC_XKEY(KP_1,            KP_1) \
    MC_XKEY(KP_2,            KP_2) \
    MC_XKEY(KP_3,            KP_3) \
    MC_XKEY(KP_4,            KP_4) \
    MC_XKEY(KP_5,            KP_5) \
    MC_XKEY(KP_6,            KP_6) \
    MC_XKEY(KP_7,            KP_7) \
    MC_XKEY(KP_8,            KP_8) \
    MC_XKEY(KP_9,            KP_9) \
    MC_XKEY(F1,              F1) \
    MC_XKEY(F2,              F2) \
    MC_XKEY(F3,              F3) \
    MC_XKEY(F4,              F4) \
    MC_XKEY(F5,              F5) \
    MC_XKEY(F6,              F6) \
    MC_XKEY(F7,              F7) \
    MC_XKEY(F8,              F8) \
    MC_XKEY(F9,              F9) \
    MC_XKEY(F10,             F10) \
    MC_XKEY(F11,             F11) \
    MC_XKEY(F12,             F12) \
    MC_XKEY(F13,             F13) \
    MC_XKEY(F14,             F14) \
    MC_XKEY(F15,             F15) \
    MC_XKEY(F16,             F16) \
    MC_XKEY(F17,             F17) \
    MC_XKEY(F18,             F18) \
    MC_XKEY(F19,             F19) \
    MC_XKEY(F20,             F20) \
    MC_XKEY(F21,             F21) \
    MC_XKEY(F22,             F22) \
    MC_XKEY(F23,             F23) \
    MC_XKEY(F24,             F24) \
    MC_XKEY(F25,             F25) \
    MC_XKEY(F26,             F26) \
    MC_XKEY(F27,             F27) \
    MC_XKEY(F28,             F28) \
    MC_XKEY(F29,             F29) \
    MC_XKEY(F30,             F30) \
    MC_XKEY(F31,             F31) \
    MC_XKEY(F32,             F32) \
    MC_XKEY(F33,             F33) \
    MC_XKEY(F34,             F34) \
    MC_XKEY(F35,             F35) \
    MC_XKEY(Shift_L,         SHIFT_L) \
    MC_XKEY(Shift_R,         SHIFT_R) \
    MC_XKEY(Control_L,       CONTROL_L) \
    MC_XKEY(Control_R,       CONTROL_R) \
    MC_XKEY(Caps_Lock,       CAPSLOCK) \
    MC_XKEY(Shift_Lock,      SHIFTLOCK) \
    MC_XKEY(Meta_L,          META_L) \
    MC_XKEY(Meta_R,          META_R) \
    MC_XKEY(Alt_L,           ALT_L) \
    MC_XKEY(Alt_R,           ALT_R) \
    MC_XKEY(Super_L,         SUPER_L) \
    MC_XKEY(Super_R,         SUPER_R) \
    MC_XKEY(Hyper_L,         HYPER_L) \
    MC_XKEY(Hyper_R,         HYPER_R) \
    MC_XKEY(space,           SPACE) \
    MC_XKEY(exclam,          EXCLAMATION) \
    MC_XKEY(quotedbl,        QUOTE) \
    MC_XKEY(numbersign,      SIGN) \
    MC_XKEY(dollar,          DOLLAR) \
    MC_XKEY(percent,         PERCENT) \
    MC_XKEY(ampersand,       AMPERSAND) \
    MC_XKEY(apostrophe,      APOSTROPHE) \
    MC_XKEY(parenleft,       PAREN_OPEN) \
    MC_XKEY(parenright,      PAREN_CLOSE) \
    MC_XKEY(asterisk,        ASTERISK) \
    MC_XKEY(plus,            PLUS) \
    MC_XKEY(comma,           COMMA) \
    MC_XKEY(minus,           MINUS) \
    MC_XKEY(period,          PERIOD) \
    MC_XKEY(slash,           SLASH) \
    MC_XKEY(0,               0) \
    MC_XKEY(1,               1) \
    MC_XKEY(2,               2) \
    MC_XKEY(3,               3) \
    MC_XKEY(4,               4) \
    MC_XKEY(5,               5) \
    MC_XKEY(6,               6) \
    MC_XKEY(7,               7) \
    MC_XKEY(8,               8) \
    MC_XKEY(9,               9) \
    MC_XKEY(colon,           COLON) \
    MC_XKEY(semicolon,       SEMICOLON) \
    MC_XKEY(less,            LESS) \
    MC_XKEY(equal,           EQUAL) \
    MC_XKEY(greater,         GREATER) \
    MC_XKEY(question,        QUESTION) \
    MC_XKEY(at,              AT) \
    MC_XKEY(A,               A) \
    MC_XKEY(B,               B) \
    MC_XKEY(C,               C) \
    MC_XKEY(D,               D) \
    MC_XKEY(E,               E) \
    MC_XKEY(F,               F) \
    MC_XKEY(G,               G) \
    MC_XKEY(H,               H) \
    MC_XKEY(I,               I) \
    MC_XKEY(J,               J) \
    MC_XKEY(K,               K) \
    MC_XKEY(L,               L) \
    MC_XKEY(M,               M) \
    MC_XKEY(N,               N) \
    MC_XKEY(O,               O) \
    MC_XKEY(P,               P) \
    MC_XKEY(Q,               Q) \
    MC_XKEY(R,               R) \
    MC_XKEY(S,               S) \
    MC_XKEY(T,               T) \
    MC_XKEY(U,               U) \
    MC_XKEY(V,               V) \
    MC_XKEY(W,               W) \
    MC_XKEY(X,               X) \
    MC_XKEY(Y,               Y) \
    MC_XKEY(Z,               Z) \
    MC_XKEY(a,               A) \
    MC_XKEY(b,               B) \
    MC_XKEY(c,               C) \
    MC_XKEY(d,               D) \
    MC_XKEY(e,               E) \
    MC_XKEY(f,               F) \
    MC_XKEY(g,               G) \
    MC_XKEY(h,               H) \
    MC_XKEY(i,               I) \
    MC_XKEY(j,               J) \
    MC_XKEY(k,               K) \
    MC_XKEY(l,               L) \
    MC_XKEY(m,               M) \
    MC_XKEY(n,               N) \
    MC_XKEY(o,               O) \
    MC_XKEY(p,               P) \
    MC_XKEY(q,               Q) \
    MC_XKEY(r,               R) \
    MC_XKEY(s,               S) \
    MC_XKEY(t,               T) \
    MC_XKEY(u,               U) \
    MC_XKEY(v,               V) \
    MC_XKEY(w,               W) \
    MC_XKEY(x,               X) \
    MC_XKEY(y,               Y) \
    MC_XKEY(z,               Z) \
    MC_XKEY(bracketleft,     BRACKET_OPEN) \
    MC_XKEY(backslash,       BACKSLASH) \
    MC_XKEY(bracketright,    BRACKET_CLOSE) \
    MC_XKEY(asciicircum,     ASCIICIRCUM) \
    MC_XKEY(underscore,      UNDERSCORE) \
    MC_XKEY(grave,           GRAVE) \
    MC_XKEY(braceleft,       BRACE_OPEN) \
    MC_XKEY(bar,             BAR) \
    MC_XKEY(braceright,      BRACE_CLOSE) \
    MC_XKEY(asciitilde,      ASCIITILDE) \
    MC_XKEY(nobreakspace,    NOBREAKSPACE) \
    MC_XKEY(exclamdown,      EXCLAMATIONDOWN) \



#endif // MC_XLIBWM_KEY_H
