#ifndef MC_WIN32WM_KEY_H
#define MC_WIN32WM_KEY_H

#define MC_WIN32_ITER_KEYS() \
    MC_VKEY(VK_BACK,        BACKSPACE) \
    MC_VKEY(VK_TAB,         TAB) \
    MC_VKEY(VK_RETURN,      RETURN) \
    MC_VKEY(VK_PAUSE,       PAUSE) \
    MC_VKEY(VK_SCROLL,      SCROLL_LOCK) \
    MC_VKEY(VK_ESCAPE,      ESCAPE) \
    MC_VKEY(VK_DELETE,      DELETE) \
    MC_VKEY(VK_HOME,        HOME) \
    MC_VKEY(VK_LEFT,        LEFT) \
    MC_VKEY(VK_UP,          UP) \
    MC_VKEY(VK_RIGHT,       RIGHT) \
    MC_VKEY(VK_DOWN,        DOWN) \
    MC_VKEY(VK_PRIOR,       PAGE_UP) \
    MC_VKEY(VK_NEXT,        PAGE_DOWN) \
    MC_VKEY(VK_END,         END) \
    MC_VKEY(VK_SELECT,      SELECT) \
    MC_VKEY(VK_PRINT,       PRINT) \
    MC_VKEY(VK_EXECUTE,     EXECUTE) \
    MC_VKEY(VK_INSERT,      INSERT) \
    MC_VKEY(VK_APPS,        MENU) \
    MC_VKEY(VK_HELP,        HELP) \
    MC_VKEY(VK_CANCEL,      CANCEL) \
    MC_VKEY(VK_MODECHANGE,  MODE_SWITCH) \
    MC_VKEY(VK_NUMLOCK,     NUM_LOCK) \
    MC_VKEY(VK_NUMPAD0,     KP_0) \
    MC_VKEY(VK_NUMPAD1,     KP_1) \
    MC_VKEY(VK_NUMPAD2,     KP_2) \
    MC_VKEY(VK_NUMPAD3,     KP_3) \
    MC_VKEY(VK_NUMPAD4,     KP_4) \
    MC_VKEY(VK_NUMPAD5,     KP_5) \
    MC_VKEY(VK_NUMPAD6,     KP_6) \
    MC_VKEY(VK_NUMPAD7,     KP_7) \
    MC_VKEY(VK_NUMPAD8,     KP_8) \
    MC_VKEY(VK_NUMPAD9,     KP_9) \
    MC_VKEY(VK_MULTIPLY,    KP_MULTIPLY) \
    MC_VKEY(VK_ADD,         KP_ADD) \
    MC_VKEY(VK_SEPARATOR,   KP_SEPARATOR) \
    MC_VKEY(VK_SUBTRACT,    KP_SUBSTRACT) \
    MC_VKEY(VK_DECIMAL,     KP_DECIMAL) \
    MC_VKEY(VK_DIVIDE,      KP_DIVIDE) \
    MC_VKEY(VK_F1,          F1) \
    MC_VKEY(VK_F2,          F2) \
    MC_VKEY(VK_F3,          F3) \
    MC_VKEY(VK_F4,          F4) \
    MC_VKEY(VK_F5,          F5) \
    MC_VKEY(VK_F6,          F6) \
    MC_VKEY(VK_F7,          F7) \
    MC_VKEY(VK_F8,          F8) \
    MC_VKEY(VK_F9,          F9) \
    MC_VKEY(VK_F10,         F10) \
    MC_VKEY(VK_F11,         F11) \
    MC_VKEY(VK_F12,         F12) \
    MC_VKEY(VK_F13,         F13) \
    MC_VKEY(VK_F14,         F14) \
    MC_VKEY(VK_F15,         F15) \
    MC_VKEY(VK_F16,         F16) \
    MC_VKEY(VK_F17,         F17) \
    MC_VKEY(VK_F18,         F18) \
    MC_VKEY(VK_F19,         F19) \
    MC_VKEY(VK_F20,         F20) \
    MC_VKEY(VK_F21,         F21) \
    MC_VKEY(VK_F22,         F22) \
    MC_VKEY(VK_F23,         F23) \
    MC_VKEY(VK_F24,         F24) \
    MC_VKEY(VK_LSHIFT,      SHIFT_L) \
    MC_VKEY(VK_RSHIFT,      SHIFT_R) \
    MC_VKEY(VK_LCONTROL,    CONTROL_L) \
    MC_VKEY(VK_RCONTROL,    CONTROL_R) \
    MC_VKEY(VK_CAPITAL,     CAPSLOCK) \
    MC_VKEY(VK_LMENU,       ALT_L) \
    MC_VKEY(VK_RMENU,       ALT_R) \
    MC_VKEY(VK_LWIN,        SUPER_L) \
    MC_VKEY(VK_RWIN,        SUPER_R) \
    MC_VKEY(VK_SPACE,       SPACE) \
    MC_VKEY('0',            0) \
    MC_VKEY('1',            1) \
    MC_VKEY('2',            2) \
    MC_VKEY('3',            3) \
    MC_VKEY('4',            4) \
    MC_VKEY('5',            5) \
    MC_VKEY('6',            6) \
    MC_VKEY('7',            7) \
    MC_VKEY('8',            8) \
    MC_VKEY('9',            9) \
    MC_VKEY('A',            A) \
    MC_VKEY('B',            B) \
    MC_VKEY('C',            C) \
    MC_VKEY('D',            D) \
    MC_VKEY('E',            E) \
    MC_VKEY('F',            F) \
    MC_VKEY('G',            G) \
    MC_VKEY('H',            H) \
    MC_VKEY('I',            I) \
    MC_VKEY('J',            J) \
    MC_VKEY('K',            K) \
    MC_VKEY('L',            L) \
    MC_VKEY('M',            M) \
    MC_VKEY('N',            N) \
    MC_VKEY('O',            O) \
    MC_VKEY('P',            P) \
    MC_VKEY('Q',            Q) \
    MC_VKEY('R',            R) \
    MC_VKEY('S',            S) \
    MC_VKEY('T',            T) \
    MC_VKEY('U',            U) \
    MC_VKEY('V',            V) \
    MC_VKEY('W',            W) \
    MC_VKEY('X',            X) \
    MC_VKEY('Y',            Y) \
    MC_VKEY('Z',            Z) \

#endif
